### ISSUE TITLE
proveWithdrawalTransaction

### ISSUE THREAD

**Issue by askucher** [superbridgeapp/superbridge-app#128]
Where is `proveWithdrawalTransaction` in source code which required by https://docs.optimism.io/stack/protocol/rollup/withdrawal-flow ?

**Comment by AlexBHarley** [comment]
Our backend populates this transaction as there are many different permutations of the data that needs to be passed depending on the rollup,

- Blast requires different data
- Fault proof proves require different data to pre fault proofs
- Kroma has a different proving model
