### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by tunerooster** [superbridgeapp/superbridge-app#131]
Superbridge is asking me to scan a qr code to connect to my metabask wallet.  However I am using Chrome's metamask plugin, on a machine with no camera.  What do I do?

P.S. Desktop Chrome  on PC running Gentoo Linux

**Comment by AlexBHarley** [comment]
Hey @tunerooster, 

Sounds like Superbridge isn't detecting the installed MetaMask extension, it then prompts you to connect via WalletConnect.

Could you get back to us on support@superbridge.app with the below info?

We'll take a closer look at this for you.

- Address of your wallet:
- Network you are bridging from:
- Network you are bridging to:
- The URL of the website you’re using to bridge:
- The browser and device you’re using:
- The geographic location you’re in:

Cheers
