### ISSUE TITLE
Can't prove withdrawal transaction on https://blast.gfxlabs.io/

### ISSUE THREAD

**Issue by tuannm91** [superbridgeapp/superbridge-app#144]
I can't prove withdrawal transaction on https://blast.gfxlabs.io/
I got the error message when call the API 
**https://api.superbridge.app/api/bridge/op_prove**
Error message: {"statusCode":500,"message":"Internal server error"}

**Comment by AlexBHarley** [comment]
Could you reach out to support@superbridge.app with your wallet address? We'll take a closer look for you.
