### ISSUE TITLE
Add to Rabby Wallet

### ISSUE THREAD

**Issue by Freedomfightersng** [superbridgeapp/superbridge-app#25]
Add superbridge to Rabby Wallet so it's easier to connect asap and bridge.

**Comment by AlexBHarley** [comment]
@Freedomfightersng do you mean add Rabby to the list of wallets supported by Superbridge? If so, this is already handled via Rainbowkit

<img width="1440" alt="Screenshot 2024-03-13 at 08 19 59" src="https://github.com/superbridgeapp/superbridge-app/assets/11168524/013ca64e-57fd-4e8d-aae7-7790e654e46b">
