### ISSUE TITLE
Failed to withdraw from OP Sepolia

### ISSUE THREAD

**Issue by hash1go** [superbridgeapp/superbridge-app#48]
I attempted to withdraw from OP Sepolia at app.optimism.io/bridge. I initiated the first withdrawal transaction on Ethereum, and here is the transaction hash.
https://sepolia.etherscan.io/tx/0x1f26c1a91342a8e620c68f1bdc42cc08e7c8356ad0e5a75fdf7d3c02b3e7dd64

I then initiated the second withdrawal transaction on superbridge.app. However, the transaction failed, and I was unable to withdraw. Here is the transaction hash.
https://sepolia.etherscan.io/tx/0x0ee7b257191dde910cb719ca436cf546ed672e74351b17715ff95710d003ce34

**Comment by AlexBHarley** [comment]
We provide support via support@superbridge.app, please reach out there with details of the problem

**Comment by hash1go** [comment]
I sent you an email. Could you please check it? Thank you.
