### ISSUE TITLE
Error when running locally

### ISSUE THREAD

**Issue by iteyelmp** [superbridgeapp/superbridge-app#50]
Hello, please tell me how to deal with this error after running the project with pnpm dev? Thanks!

bridge:dev:  ⨯ AxiosError [AggregateError]
bridge:dev:     at AxiosError.from (file:///Users/IdeaProjects/superbridge-app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/AxiosError.js:89:14)
bridge:dev:     at RedirectableRequest.handleRequestError (file:///Users/IdeaProjects/superbridge-app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:610:25)
bridge:dev:     at RedirectableRequest.emit (node:events:519:28)
bridge:dev:     at eventHandlers.<computed> (/Users/IdeaProjects/superbridge-app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24)
bridge:dev:     at ClientRequest.emit (node:events:519:28)
bridge:dev:     at Socket.socketErrorListener (node:_http_client:500:9)
bridge:dev:     at Socket.emit (node:events:519:28)
bridge:dev:     at emitErrorNT (node:internal/streams/destroy:169:8)
bridge:dev:     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
bridge:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
bridge:dev:     at Axios.request (file:///Users/IdeaProjects/superbridge-app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41)
bridge:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bridge:dev:     at async getServerSideProps (webpack-internal:///./pages/[[...index]].tsx:101:26) {
bridge:dev:   code: 'ECONNREFUSED',
bridge:dev:   errors: [
bridge:dev:     Error: connect ECONNREFUSED ::1:80
bridge:dev:         at createConnectionError (node:net:1647:14)
bridge:dev:         at afterConnectMultiple (node:net:1677:16) {
bridge:dev:       errno: -61,
bridge:dev:       code: 'ECONNREFUSED',
bridge:dev:       syscall: 'connect',
bridge:dev:       address: '::1',
bridge:dev:       port: 80
bridge:dev:     },
bridge:dev:     Error: connect ECONNREFUSED 127.0.0.1:80
bridge:dev:         at createConnectionError (node:net:1647:14)
bridge:dev:         at afterConnectMultiple (node:net:1677:16) {
bridge:dev:       errno: -61,
bridge:dev:       code: 'ECONNREFUSED',
bridge:dev:       syscall: 'connect',
bridge:dev:       address: '127.0.0.1',
bridge:dev:       port: 80
bridge:dev:     }
bridge:dev:   ],
bridge:dev:   config: {
bridge:dev:     transitional: {
bridge:dev:       silentJSONParsing: true,
bridge:dev:       forcedJSONParsing: true,
bridge:dev:       clarifyTimeoutError: false
bridge:dev:     },
bridge:dev:     adapter: [ 'xhr', 'http' ],
bridge:dev:     transformRequest: [ [Function: transformRequest] ],
bridge:dev:     transformResponse: [ [Function: transformResponse] ],
bridge:dev:     timeout: 0,
bridge:dev:     xsrfCookieName: 'XSRF-TOKEN',
bridge:dev:     xsrfHeaderName: 'X-XSRF-TOKEN',
bridge:dev:     maxContentLength: -1,
bridge:dev:     maxBodyLength: -1,
bridge:dev:     env: { FormData: [Function], Blob: [class Blob] },
bridge:dev:     validateStatus: [Function: validateStatus],
bridge:dev:     headers: Object [AxiosHeaders] {
bridge:dev:       Accept: 'application/json, text/plain, */*',
bridge:dev:       'Content-Type': undefined,
bridge:dev:       'User-Agent': 'axios/1.6.8',
bridge:dev:       'Accept-Encoding': 'gzip, compress, deflate, br'
bridge:dev:     },
bridge:dev:     params: { names: [Array] },
bridge:dev:     method: 'get',
bridge:dev:     url: '/api/bridge/deployments',
bridge:dev:     data: undefined
bridge:dev:   },
bridge:dev:   request: <ref *1> Writable {
bridge:dev:     _events: {
bridge:dev:       close: undefined,
bridge:dev:       error: [Function: handleRequestError],
bridge:dev:       prefinish: undefined,
bridge:dev:       finish: undefined,
bridge:dev:       drain: undefined,
bridge:dev:       response: [Function: handleResponse],
bridge:dev:       socket: [Function: handleRequestSocket]
bridge:dev:     },
bridge:dev:     _writableState: WritableState {
bridge:dev:       highWaterMark: 16384,
bridge:dev:       length: 0,
bridge:dev:       corked: 0,
bridge:dev:       onwrite: [Function: bound onwrite],
bridge:dev:       writelen: 0,
bridge:dev:       bufferedIndex: 0,
bridge:dev:       pendingcb: 0,
bridge:dev:       [Symbol(kState)]: 17580812,
bridge:dev:       [Symbol(kBufferedValue)]: null
bridge:dev:     },
bridge:dev:     _maxListeners: undefined,
bridge:dev:     _options: {
bridge:dev:       maxRedirects: 21,
bridge:dev:       maxBodyLength: Infinity,
bridge:dev:       protocol: 'http:',
bridge:dev:       path: '/api/bridge/deployments?names[]=arbitrum-one',
bridge:dev:       method: 'GET',
bridge:dev:       headers: [Object: null prototype],
bridge:dev:       agents: [Object],
bridge:dev:       auth: undefined,
bridge:dev:       family: undefined,
bridge:dev:       beforeRedirect: [Function: dispatchBeforeRedirect],
bridge:dev:       beforeRedirects: [Object],
bridge:dev:       hostname: 'localhost',
bridge:dev:       port: '',
bridge:dev:       agent: undefined,
bridge:dev:       nativeProtocols: [Object],
bridge:dev:       pathname: '/api/bridge/deployments',
bridge:dev:       search: '?names[]=arbitrum-one'
bridge:dev:     },
bridge:dev:     _ended: true,
bridge:dev:     _ending: true,
bridge:dev:     _redirectCount: 0,
bridge:dev:     _redirects: [],
bridge:dev:     _requestBodyLength: 0,
bridge:dev:     _requestBodyBuffers: [],
bridge:dev:     _eventsCount: 3,
bridge:dev:     _onNativeResponse: [Function (anonymous)],
bridge:dev:     _currentRequest: ClientRequest {
bridge:dev:       _events: [Object: null prototype],
bridge:dev:       _eventsCount: 7,
bridge:dev:       _maxListeners: undefined,
bridge:dev:       outputData: [],
bridge:dev:       outputSize: 0,
bridge:dev:       writable: true,
bridge:dev:       destroyed: true,
bridge:dev:       _last: true,
bridge:dev:       chunkedEncoding: false,
bridge:dev:       shouldKeepAlive: true,
bridge:dev:       maxRequestsOnConnectionReached: false,
bridge:dev:       _defaultKeepAlive: true,
bridge:dev:       useChunkedEncodingByDefault: false,
bridge:dev:       sendDate: false,
bridge:dev:       _removedConnection: false,
bridge:dev:       _removedContLen: false,
bridge:dev:       _removedTE: false,
bridge:dev:       strictContentLength: false,
bridge:dev:       _contentLength: 0,
bridge:dev:       _hasBody: true,
bridge:dev:       _trailer: '',
bridge:dev:       finished: true,
bridge:dev:       _headerSent: true,
bridge:dev:       _closed: true,
bridge:dev:       socket: [Socket],
bridge:dev:       _header: 'GET /api/bridge/deployments?names[]=arbitrum-one HTTP/1.1\r\n' +
bridge:dev:         'Accept: application/json, text/plain, */*\r\n' +
bridge:dev:         'User-Agent: axios/1.6.8\r\n' +
bridge:dev:         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
bridge:dev:         'Host: localhost\r\n' +
bridge:dev:         'Connection: keep-alive\r\n' +
bridge:dev:         '\r\n',
bridge:dev:       _keepAliveTimeout: 0,
bridge:dev:       _onPendingData: [Function: nop],
bridge:dev:       agent: [Agent],
bridge:dev:       socketPath: undefined,
bridge:dev:       method: 'GET',
bridge:dev:       maxHeaderSize: undefined,
bridge:dev:       insecureHTTPParser: undefined,
bridge:dev:       joinDuplicateHeaders: undefined,
bridge:dev:       path: '/api/bridge/deployments?names[]=arbitrum-one',
bridge:dev:       _ended: false,
bridge:dev:       res: null,
bridge:dev:       aborted: false,
bridge:dev:       timeoutCb: [Function: emitRequestTimeout],
bridge:dev:       upgradeOrConnect: false,
bridge:dev:       parser: null,
bridge:dev:       maxHeadersCount: null,
bridge:dev:       reusedSocket: false,
bridge:dev:       host: 'localhost',
bridge:dev:       protocol: 'http:',
bridge:dev:       _redirectable: [Circular *1],
bridge:dev:       [Symbol(shapeMode)]: false,
bridge:dev:       [Symbol(kCapture)]: false,
bridge:dev:       [Symbol(kBytesWritten)]: 0,
bridge:dev:       [Symbol(kNeedDrain)]: false,
bridge:dev:       [Symbol(corked)]: 0,
bridge:dev:       [Symbol(kOutHeaders)]: [Object: null prototype],
bridge:dev:       [Symbol(errored)]: null,
bridge:dev:       [Symbol(kHighWaterMark)]: 16384,
bridge:dev:       [Symbol(kRejectNonStandardBodyWrites)]: false,
bridge:dev:       [Symbol(kUniqueHeaders)]: null
bridge:dev:     },
bridge:dev:     _currentUrl: 'http://localhost/api/bridge/deployments?names[]=arbitrum-one',
bridge:dev:     [Symbol(shapeMode)]: true,
bridge:dev:     [Symbol(kCapture)]: false
bridge:dev:   },
bridge:dev:   cause: AggregateError [ECONNREFUSED]: 
bridge:dev:       at internalConnectMultiple (node:net:1117:18)
bridge:dev:       at afterConnectMultiple (node:net:1684:7) {
bridge:dev:     code: 'ECONNREFUSED',
bridge:dev:     [errors]: [ [Error], [Error] ]
bridge:dev:   },
bridge:dev:   page: '/'
bridge:dev: }

<img width="975" alt="image" src="https://github.com/superbridgeapp/superbridge-app/assets/6647261/46a1171b-0f57-44fc-af7e-8f14c5938c1e">
<img width="552" alt="image" src="https://github.com/superbridgeapp/superbridge-app/assets/6647261/974ebf38-d6e6-4f2b-9227-a0f9bf283d46">
<img width="701" alt="image" src="https://github.com/superbridgeapp/superbridge-app/assets/6647261/d6617ac5-dc9c-43c1-8bd1-5454a82fe796">

**Comment by AlexBHarley** [comment]
My guess is you haven't setup your `.env` file. See `.env.example` for reference.
