### ISSUE TITLE
Custom gas token support

### ISSUE THREAD

**Issue by qzhodl** [superbridgeapp/superbridge-app#57]
Since the beta version of the custom gas token feature is now live for the OP Stack (as mentioned in [this tweet](https://x.com/OPLabsPBC/status/1795933890617438601)), do you have plans to support it on RollBridge?

**Comment by AlexBHarley** [comment]
@qzhodl custom gas token support is already live. Please reach out to support@superbridge.app if you're having issues with a specific chain

**Comment by qzhodl** [comment]
> @qzhodl custom gas token support is already live. Please reach out to [support@superbridge.app](mailto:support@superbridge.app) if you're having issues with a specific chain

Oh, cool! Is there any UI on SuperBridge where we can test this feature? I’ve tested the OP-Sepolia UI on SuperBridge, but I couldn’t find an entry to test the native gas token bridge.

**Comment by AlexBHarley** [comment]
Yeah OP Sepolia doesn’t have a custom gas token.

You could spin up a custom gas network via Conduit, then launch a bridge UI from their dashboard and test it out.
