### ISSUE TITLE
how to run superbridge in local

### ISSUE THREAD

**Issue by Delaube923** [superbridgeapp/superbridge-app#68]
i git clone this code , and then i use npm run dev to depolyed locally. it has errros. how can i fix it 
No locally installed `turbo` found. Using version: 2.0.3.
  × found `pipeline` field instead of `tasks`
    ╭─[turbo.json:3:1]
  3 │       "globalDependencies": ["**/.env.*local"],
  4 │ ╭─▶   "pipeline": {
  5 │ │       "build": {
  6 │ │         "dependsOn": ["^build"],
  7 │ │         "outputs": [".next/**", "!.next/cache/**"]
  8 │ │       },
  9 │ │       "lint": {},
 10 │ │       "dev": {
 11 │ │         "cache": false,
 12 │ │         "persistent": true
 13 │ │       }
 14 │ ├─▶   }
    · ╰──── rename `pipeline` field to `tasks`
 15 │     }
    ╰────
  help: changed in 2.0: `pipeline` has been renamed to `tasks`

**Comment by AlexBHarley** [comment]
We use `pnpm` not `npm`. I think you might also need a `.env` file in `apps/bridge`

**Comment by yucheng-Li** [comment]
<img width="1185" alt="image" src="https://github.com/superbridgeapp/superbridge-app/assets/61103353/907af74b-d85f-4894-8c13-19dacf010cb5">
I had created a  .env file from .env.example file, but i got this error, has something i need to config ? 

@AlexBHarley
