### ISSUE TITLE
Add support for Lambda Chain.

### ISSUE THREAD

**Issue by haistack** [superbridgeapp/superbridge-app#73]
Hello, how can I add support for a new network? I want to integrate Lambda Chain into the project. I tried modifying the code for theme, superchainbridge, and token-list, but it did not achieve the desired results. Please help me.

Lambda Chain is an Ethereum Layer 2 network based on the OP Stack.

**Comment by AlexBHarley** [comment]
See https://superbridge.app/rollies for getting a new deployment
