### ISSUE TITLE
AxiosError: Request failed with status code 401 

### ISSUE THREAD

**Issue by yucheng-Li** [superbridgeapp/superbridge-app#77]
When i run superbridge app local i meet this problem, i had add the .env file from .env.example, has something i need to config?
<img width="1100" alt="image" src="https://github.com/superbridgeapp/superbridge-app/assets/61103353/f00ce850-7834-44de-a06b-33115ecc00ee">

**Comment by AlexBHarley** [comment]
You need an API key to hit the backend. We were getting flooded with requests so now we restrict access.

Do you want to ping Alex_B_H on Telegram and I can help get you setup with one?

**Comment by yucheng-Li** [comment]
已收到

**Comment by xQuotes** [comment]
How to get an API key ?

**Comment by yucheng-Li** [comment]
已收到
