### ISSUE TITLE
CCTP USDC mint doesn't work

### ISSUE THREAD

**Issue by ssnerd** [superbridgeapp/superbridge-app#84]
address: `0xAD09780d193884d503182aD4588450C416D6F9D4`

I bridge from Ethereum mainnet to Base mainnet. Already deposited and burnt USDC on Ethereum. But on Base, I can't mint

**Comment by AlexBHarley** [comment]
I can't see any transactions from that address, could you reach out to support@superbridge.app with the transaction hash in question?

We'll take a closer look.

**Comment by ssnerd** [comment]
Oh sorry, it's not my address. It's the contract address that fails interaction. I already shared my address and transaction hash via that support email. Thanks
